lang = "Rust"
dir = "."
spec_url = "/openapi.json"

[services."@ginger-society/IAMService"]
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"
dev = "http://localhost:8080/iam"

[services."@ginger-society/MetadataService"]
dev = "http://localhost:8081/metadata"
stage = "https://api-staging.gingersociety.org/metadata"
stage_k8 = "http://metadata-service-api-service/metadata"

[portals_refs]

[urls]
dev = "http://localhost:8081"
prod = "https://exampleapi.com"
stage = "https://exampleapi.com"
