lang = "Rust"
dir = "."
spec_url = "/openapi.json"

[services.IAMService]
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[services.MetadataService]
stage_k8 = "http://metadata-service-api-service/metadata"
stage = "https://api-staging.gingersociety.org/metadata"

[urls]
stage = "https://exampleapi.com"
dev = "http://localhost:8081"
prod = "https://exampleapi.com"
