dir = "."
lang = "Rust"
spec_url = "/openapi.json"

[urls]
dev = "http://localhost:8081"
prod = "https://exampleapi.com"
stage = "https://exampleapi.com"

[services.MetadataService]
dev = "http://localhost:8081"

[services.IAMService]
dev = "http://localhost:8080"
